export enum CompanyErrorCode {
  PROFILE_ALREADY_EXISTS = 'CO001',
  PROFILE_NOT_FOUND = 'CO002',
  PROFILE_ALREADY_CLAIMED = 'CO003',
  INVALID_INVITATION_TOKEN = 'CO004',
  CUSTOMER_NOT_FOUND = 'CO005',
  INSUFFICIENT_CREDIT_BALANCE = 'CO006',
}
